spring:
  profiles:
    active: test1
    #test5为前端环境 服务器上配置时请使用test5打包


#公共配置

mybatis-plus:
  configuration:
    #数据库下划线命名到java驼峰命名 默认为true
    map-underscore-to-camel-case: true
    #控制台打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑删除的字段名
      logic-delete-field: deleted
      #逻辑删除的值 1表示已删除
      logic-delete-value: 1
      #0表示未删除
      logic-not-delete-value: 0
