#开发环境
server:
  port: 8080

spring:
  datasource:
    #数据库驱动完整类名
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接url
    url: jdbc:mysql://localhost:3306/recruitment_test1?characterEncoding=utf-8
    #数据库用户名
    username: root
    #数据库密码
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379

